### ISSUE TITLE
PayPal not work for Android

### ISSUE THREAD

**Issue by FetFrumos** [Pikaju/FlutterBraintree#180]
I used last version plugin 4.0.0. But PayPal not work for Android.  for ios it works. I test in the sandbox - but after trying to pay, the flow does not return to the application. I am getting the following error:

```
E/AndroidRuntime(29771): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.api.DropInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
E/AndroidRuntime(29771): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3780)
E/AndroidRuntime(29771): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3947)
E/AndroidRuntime(29771): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)
E/AndroidRuntime(29771): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(29771): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(29771): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
E/AndroidRuntime(29771): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(29771): 	at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime(29771): 	at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime(29771): 	at android.app.ActivityThread.main(ActivityThread.java:8280)
E/AndroidRuntime(29771): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29771): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
E/AndroidRuntime(29771): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
E/AndroidRuntime(29771): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
E/AndroidRuntime(29771): 	at com.braintreepayments.api.DropInActivity.getDropInRequest(DropInActivity.java:124)
E/AndroidRuntime(29771): 	at com.braintreepayments.api.DropInActivity.onCreate(DropInActivity.java:78)
E/AndroidRuntime(29771): 	at android.app.Activity.performCreate(Activity.java:8163)
E/AndroidRuntime(29771): 	at android.app.Activity.performCreate(Activity.java:8130)
E/AndroidRuntime(29771): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
E/AndroidRuntime(29771): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3753)
E/AndroidRuntime(29771): 	... 12 more
```

is there an update planned? maybe someone solved this issue?

**Comment by BunnyBuddy** [comment]
Yea this ones a head scratcher, couldn't figure it out. 
I believe it originates from the native SDK and mostly occurs on Android 14 (for me). 
Have you checked this on other android versions?

**Comment by knight-dev** [comment]
Same here

**Comment by BIGSMSDev1** [comment]
Really need this fixed. We can't take payments through paypal until this is fixed. Any workarounds for this?

**Comment by BunnyBuddy** [comment]
> Really need this fixed. We can't take payments through paypal until this is fixed. Any workarounds for this?

I have abandoned this package entirely and created my own braintree package which uses native sdks (instead of dropin), will be uploading as soon as I get some free time. 
It wont be the cleanest but I am sure it gets the job done without worrying about deprecations.
