### ISSUE TITLE
Crash after upgrading to Flutter 1.12

### ISSUE THREAD

**Issue by philipgiuliani** [Pikaju/FlutterBraintree#6]
For some reason `activeResults` is null onActivityResult. I tried to debug it but couldn't find out whats the problem.

```
E/AndroidRuntime(27603): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4919, result=0, data=null} to activity {express.skorpion.app/express.skorpion.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(27603): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime(27603): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime(27603): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(27603): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(27603): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(27603): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(27603): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(27603): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(27603): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(27603): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27603): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(27603): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(27603): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(27603): 	at com.example.flutter_braintree.FlutterBraintreeDropIn.onActivityResult(FlutterBraintreeDropIn.java:129)
E/AndroidRuntime(27603): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime(27603): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime(27603): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime(27603): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime(27603): 	at android.app.Activity.dispatchActivityResult(Activity.java:8135)
E/AndroidRuntime(27603): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime(27603): 	... 11 more
```

**Comment by Pikaju** [comment]
Could you give me more details so I can reproduce the bug? I switched to Flutter version v1.12.13+hotfix.5 (the stable branch) and played around with the example app. It seems to be working fine.

**Comment by philipgiuliani** [comment]
Hi,
it only happens when you generate a new Flutter app or migrate the current app with the following steps: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#full-flutter-app-migration.

Seems there is some incompatibility with the V1 Plugin Engine... 🤔

**Comment by Pikaju** [comment]
I believe I fixed the issue in 57dda953a4ce660fc1cfce68fcd4b8d9f45939c5. Could you please verify that it works now?

**Comment by philipgiuliani** [comment]
Hi! It works now 🎉👏.

There is a warning displayed now when I am compiling my app.
```
Note: $HOME/.pub-cache/git/FlutterBraintree-57dda953a4ce660fc1cfce68fcd4b8d9f45939c5/android/src/main/java/com/example/flutter_braintree/FlutterBraintreePlugin.java uses unchecked or unsafe operations.
```

Also, you can delete the `flutter_braintree_example/MainActivity.java` now.

**Comment by Pikaju** [comment]
Hey, thank you for verifying. I deleted the file and got rid of the linter warnings. Version `0.5.3` includes the recent changes.
